export const servicePages = [
  { slug: 'creation-site-web-maroc', title: 'Création de site web au Maroc', service: 'Création de site web', location: 'Maroc', intro: 'GoSite conçoit des sites rapides, accessibles et orientés conversion pour les entreprises marocaines qui veulent gagner en crédibilité et générer des opportunités.', benefits: ['Design sur mesure et responsive', 'SEO technique dès la conception', 'Performance Core Web Vitals', 'Accompagnement après mise en ligne'] },
  { slug: 'developpeur-wordpress-casablanca', title: 'Développeur WordPress à Casablanca', service: 'Développement WordPress', location: 'Casablanca', intro: 'Sahab Youssef développe avec GoSite des sites WordPress maintenables, rapides et simples à administrer pour les entreprises de Casablanca.', benefits: ['WordPress et WooCommerce', 'Bricks Builder et composants sur mesure', 'Migration et optimisation', 'Maintenance proactive'] },
  { slug: 'developpement-nextjs-maroc', title: 'Développement Next.js au Maroc', service: 'Développement Next.js', location: 'Maroc', intro: 'Des applications web modernes en Next.js, pensées pour la vitesse, l’évolutivité et une excellente expérience utilisateur.', benefits: ['Architecture App Router', 'TypeScript et API sécurisées', 'Déploiement Vercel', 'SEO et rendu serveur'] },
  { slug: 'seo-technique-maroc', title: 'Consultant SEO technique au Maroc', service: 'SEO technique', location: 'Maroc', intro: 'GoSite identifie et corrige les freins techniques qui limitent l’exploration, l’indexation et la performance organique de votre site.', benefits: ['Audit technique priorisé', 'Données structurées', 'Core Web Vitals', 'Plan de mesure GA4 et Search Console'] },
  { slug: 'web-agency-in-morocco', title: 'Web agency in Morocco for international projects', service: 'Web development', location: 'Morocco & worldwide', intro: 'GoSite helps international teams launch fast, multilingual and search-ready digital experiences with a reliable Morocco-based technical partner.', benefits: ['English and French delivery', 'WordPress and Next.js expertise', 'International SEO foundations', 'Clear async collaboration'] },
] as const

export type ServicePage = (typeof servicePages)[number]
